task:
    name: new
    timeout_in: 122m
    container:
      image: ubuntu:20.04
      cpu: 8
      memory: 30G 
    env_script:
      - bash env     
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache

#start build 

