task:
    name: new
    timeout_in: 122m
    container:
      image: fr3akyphantom/droid-builder:latest
      cpu: 8
      memory: 30G 
    sync_script:
      - bash sync
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache

#start build 

