#!/bin/bash
cd /tmp/rom
rm -rf .repo
source build/envsetup.sh
lunch lineage_m01q-userdebug
export ALLOW_MISSING_DEPENDENCIES=true
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 20G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	mka bacon -j8
	zip=$(up out/target/product/m01q/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom 
