#!/bin/bash

url=https://mirrorbot.thecloverly.workers.dev/0://ccache-ppui.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-ppui.tar.gz
echo "unzip done"
find ccache-ppui.tar.gz -delete
