#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=10.0

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --depth=1 --no-repo-verify -u git://github.com/crdroidandroid/android.git -b 10.0 -g default,-mips,-darwin,-notdefault
git config --global user.name "SriBalaji"
git config --global user.email "sribalajisenthilkumar@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/horoidrom/m01q.git device/samsung/m01q
git clone https://github.com/horoidrom/439-com.git device/samsung/sdm439-common

cd /tmp/rom
