#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/DerpFest-11/manifest.git
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u git://github.com/DerpFest-11/manifest.git -b 11
git config --global user.name "SriBalaji"
git config --global user.email "sribalajisenthilkumar@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync --force-sync --no-tags --no-clone-bundle

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/ashuk1109/vendor_realme_RMX2001.git vendor/realme/RMX2001
git clone https://github.com/TheCloverly/RevengeOS_device_realme_RMX2001 device/realme/RMX2001

cd /tmp/rom
